apiVersion: v1
kind: Secret
metadata:
  name: db-migration-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: "mysql-service.database.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "modules_db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
